# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:testing"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/caja-extensions
    - caja
    - dbus-glib
    - gcc
    - git
    - gupnp
    - imagemagick
    - intltool
    - make
    - mate-common
    - python
    - samba
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja-extensions
    - git
    - libcaja-extension-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgtk-3-dev
    - libgupnp-1.0-dev
    - libmate-desktop-dev
    - libstartup-notification0-dev
    - make
    - mate-common
    - pkg-config

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja-extensions.git
    - caja-devel
    - dbus-glib-devel
    - dbus-glib-devel
    - gajim
    - gcc
    - git
    - gtk3-devel
    - gupnp-devel
    - make
    - mate-common
    - mate-desktop-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - libcaja-extension-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgtk-3-dev
    - libgupnp-1.2-dev
    - libmate-desktop-dev
    - libstartup-notification0-dev
    - make
    - mate-common
    - pkg-config

variables:
  - CFLAGS="-Wall -Werror=format-security"

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: caja-extensions-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
